---
# tasks file for samba_ou_create

- name: Check if the registry is there
  shell: /usr/bin/host -t "{{ type }}" "{{ name }}.{{ zone }}"
  changed_when: False
  failed_when: False
  register: dns_q

- name: Create the record 
  shell: /usr/bin/samba-tool dns "{{ action }}" "{{ server }}" "{{ zone }}" "{{ name }}" "{{ type }}" "{{ data }}" -U "{{ user }}" --password="{{ password }}"
  when:
    - "'add' in action"
    - ('not found' in dns_q.stdout or 'has no' in dns_q.stdout )
    
- name: Delete the record 
  shell: /usr/bin/samba-tool dns "{{ action }}" "{{ server }}" "{{ zone }}" "{{ name }}" "{{ type }}" "{{ data }}" -U "{{ user }}" --password="{{ password }}"
  when:
    - "'delete' in action"
    - not ('not found' in dns_q.stdout or 'has no' in dns_q.stdout )
    
  