---
# tasks file for samba_groups

# Available subcommands:
#   add            - Creates a new AD group.
#   addmembers     - Add members to an AD group.
#   delete         - Deletes an AD group.
#   edit           - Modify Group AD object.
#   list           - List all groups.
#   listmembers    - List all members of an AD group.
#   move           - Move a group to an organizational unit/container.
#   removemembers  - Remove members from an AD group.
#   show           - Display a group AD object.
#   stats          - Summary statistics about group memberships.


### Checks
- name: Get the group list
  shell: samba-tool group list
  register: group_filter
  changed_when: False
  failed_when: False

- name: Get the users from a group
  shell: samba-tool group listmembers "{{ group|lower }}"
  register: user_filter
  changed_when: False
  failed_when: False 
  when:
    - group in group_filter.stdout_lines
    - "action == 'addmembers'"

### Some fails checks

- name: "Fail check: Add user to a group: non existent group"
  fail: "Fail: you asked to add the user(s) {{ users }} to the group {{ group }}, but this group does not exist" 
  when:
    - "action == 'addmembers'"
    - group not in group_filter.stdout_lines

### Create a group
# Group - email - ou
- name: Create a group [ - email - ou ]
  shell: samba-tool group "{{ action }}" "{{ group }}" --description="{{ description }}" -U "{{ auth_user }}" --password="{{ password }}"
  when:
    - "action == 'add'"
    - group not in group_filter.stdout_lines
    - group_mail|length == 0
    - group_ou|length == 0

# Group + email - ou
- name: Create a group [ + email - ou ]
  shell: samba-tool group "{{ action }}" "{{ group }}" --description="{{ description }}" --mail-address="{{ group_mail }}" -U "{{ auth_user }}" --password="{{ password }}"
  when:
    - "action == 'add'"
    - group not in group_filter.stdout_lines
    - group_mail|length > 0
    - group_ou|length == 0

# Group - email + ou
- name: Create a group [ - email + ou ]
  shell: samba-tool group "{{ action }}" "{{ group }}" --description="{{ description }}" --groupou="{{ group_ou }}" -U "{{ auth_user }}" --password="{{ password }}"
  when:
    - "action == 'add'"
    - group not in group_filter.stdout_lines
    - group_mail|length == 0
    - group_ou|length > 0

# Group + email + ou
- name: Create a group [ + email + ou ]
  shell: samba-tool group "{{ action }}" "{{ group }}" --description="{{ description }}"  --groupou="{{ group_ou }}" --mail-address="{{ group_mail }}" -U "{{ auth_user }}" --password="{{ password }}"
  when:
    - "action == 'add'"
    - group not in group_filter.stdout_lines
    - group_mail|length > 0
    - group_ou|length > 0

### Delete a group
- name: Delete a group
  shell: samba-tool group "{{ action }}" "{{ group }}" -U "{{ auth_user }}" --password="{{ password }}"
  when:
    - "action == 'delete'"
    - group in group_filter.stdout_lines

### Add user/users to a group
- name: Add user to a group
  shell: samba-tool group "{{ action }}" "{{ group }}" "{{ users }}" -U "{{ auth_user }}" --password="{{ password }}"
  when:
    - "action == 'addmembers'"
    - group in group_filter.stdout_lines
    - users not in user_filter.stdout_lines
