---
# vars file for nginx_site

- name: Check if destination folder exist
  stat:
    path: "{{ site_root }}"
  register: root_exists

- name: Create the destination folder if needed
  file:
    path: "{{ site_root }}"
    state: directory
    mode: 0775
    owner: www-data
    group: www-data
  when: not root_exists.stat.exists|bool

- name: Create the site file if needed
  template:
    src: ../templates/default.j2
    dest: /etc/nginx/sites-available/{{ site_filename }}

- name: Create the link to activate the new site
  file:
    state: link
    src: /etc/nginx/sites-available/{{ site_filename }}
    path: /etc/nginx/sites-enabled/{{ site_filename }}
  notify:
    - Nginx test
    - Nginx restart
