# Pavel Milanes [pavelmc@gamil.com] 2021
#
# Target: install &  configure a samba server

---
- name: Install the samba 4 domain controller and configure it
  hosts: dc
  remote_user: root
  vars_files:
    - "../vars/domain.yml"

  tasks:

  - name: Samba install
    package:
      name:
        - samba
        - winbind
      state: present

  - name: Remove default configuration
    file:
      path: "{{ item }}"
      state: absent
    with_items:
    - /etc/krb5.conf
    - /etc/samba/smb.conf
    - /var/lib/samba/private/tls
    ignore_errors: True

  - name: Create AD Domain Configuration
    command: samba-tool domain provision --use-rfc2307 \
      --realm {{ samba_realm }} --domain {{ samba_netbios }} \
      --server-role=dc --dns-backend=SAMBA_INTERNAL \
      --adminpass={{ samba_adminpass }}

  - name: Create krb5.conf
    template:
      src: ../templates/{{ ansible_hostname }}/etc/krb5.conf.j2
      dest: /etc/krb5.conf
      owner: root
      group: root
      mode: '0644'
      backup: yes

  - name: Kerberos user conf install
    ansible.builtin.apt:
      name: krb5-user
      state: latest

  - name: Disable & stop systemd-resolved service
    ansible.builtin.systemd:
      name: systemd-resolved.service
      enabled: no
      masked: yes
      state: stopped

  - name: Disable nmbd samba standalone service
    ansible.builtin.systemd:
      name: nmbd
      enabled: no
      masked: yes
      state: stopped

  - name: Disable smbd samba standalone service
    ansible.builtin.systemd:
      name: smbd
      enabled: no
      masked: yes
      state: stopped

  - name: Enable & start Samba AD-DC service
    ansible.builtin.systemd :
      name: samba-ad-dc
      enabled: yes
      masked: no
      state: restarted

