# Pavel Milanes [pavelmc@gmail.com] 2021
#
# Target: install &  configure a samba server

---
- name: Install the samba 4 domain controller and configure it
  hosts: dc
  remote_user: root
  vars_files:
    - "../vars/secrets.yml"
    - "../vars/domain.yml"

  tasks:
    - name: Validation for netbios vs realm ({{ samba.netbios }} / {{ samba.realm }})
      fail:
        msg: "Samba NETBIOS must be shorter and not equal than REALM"
      when: samba.realm == samba.netbios

    - name: Samba install
      package:
        name:
          - samba
          - winbind
        state: present
    
    - name: Remove default configuration files
      file:
        path: "{{ item }}"
        state: absent
      with_items:
        - /etc/krb5.conf
        - /etc/samba/smb.conf
      ignore_errors: True

    - name: Find old db files of samba
      find:
        paths: /var/lib/samba
        use_regex: False
        recurse: True
        patterns:
          - '*.tdb'
          - '*.ldb'
          - '*.key'
          - '*tls'
          - '*conf.update'
      register: db_to_del
    
    - name: Remove old provision files
      file:
        path: "{{ item.path }}"
        state: absent
      with_items:
        - "{{ db_to_del.files }}"

    - name: Create AD Domain Configuration
      command: samba-tool domain provision --use-rfc2307 \
        --realm {{ samba.realm }} --domain {{ samba.netbios }} \
        --server-role=dc --dns-backend=SAMBA_INTERNAL \
        --adminpass={{ samba_adminpass }}

    - name: Create krb5.conf
      template:
        src: ../templates/{{ ansible_hostname }}/etc/krb5.conf.j2
        dest: /etc/krb5.conf
        owner: root
        group: root
        mode: '0644'
        backup: yes

    - name: Kerberos user conf install
      ansible.builtin.apt:
        name: krb5-user
        state: latest

    - name: Disable & stop needed services
      ansible.builtin.systemd:
        name: "{{ item }}"
        enabled: no
        masked: yes
        state: stopped
      with_items:
        - smbd
        - nmbd
        - winbind
        - systemd-resolved

    - name: Enable & start Samba AD-DC service
      ansible.builtin.systemd :
        name: samba-ad-dc
        enabled: yes
        masked: no
        state: restarted

