# Pavel Milanes [pavelmc@gamil.com] 2021
#
# Target: configure a local repository for all the nodes
#
# Requisite: Create all CTs we need as per host vars

---
- name: Setup a local repository for all the nodes
  hosts: ct
  remote_user: root
  vars_files:
    - "../vars/domain.yml"
    - "../vars/cts.yml"

  tasks:
    - name: Replace default sources.list with a custom one
      template:
        src: ../templates/cts/etc/apt/sources.list.j2
        dest: /etc/apt/sources.list
        owner: root
        group: root
        mode: '0644'
        backup: yes

    - name: Update apt repo and cache on all Debian/Ubuntu boxes
      apt: update_cache=yes force_apt_get=yes cache_valid_time=259200

    - name: Upgrade all packages on servers
      apt: upgrade=dist force_apt_get=yes
    
